CREATE TABLE AJUSTES(
ID INTEGER PRIMARY KEY AUTOINCREMENT, 
IS_OTG_DELAY_ACTIVE INTEGER DEFAULT 0,
OTG_DELAY INTEGER DEFAULT 0,
OPEN_KEYBOARD_AFTER INTEGER DEFAULT 0
);
INSERT INTO AJUSTES (IS_OTG_DELAY_ACTIVE,OTG_DELAY,OPEN_KEYBOARD_AFTER) VALUES(0,0,0);

CREATE TABLE PERFIL_USUARIO (
ID INTEGER PRIMARY KEY AUTOINCREMENT, 
ID_DISPOSITIVO TEXT NOT NULL,
NOMBRE TEXT NOT NULL DEFAULT '',
NOMBRE_ALMACEN TEXT NOT NULL DEFAULT '',
ID_ALMACEN INTEGER NOT NULL DEFAULT -1
);

CREATE TABLE INVENTARIO_MOVIL (
ID INTEGER PRIMARY KEY AUTOINCREMENT,
ID_ALMACEN INTEGER NOT NULL,
GUID TEXT NOT NULL UNIQUE,
ARTICULOS_INVENTARIADOS INTEGER NOT NULL DEFAULT 0,
LINEAS_INVENTARIADAS  INTEGER NOT NULL DEFAULT 0,
FECHA_INICIO TEXT,
FECHA_FIN TEXT,
CONFIRMADO INTEGER NOT NULL DEFAULT 0,
CONCENTRADO INTEGER NOT NULL DEFAULT 0,
ELIMINADO INTEGER NOT NULL DEFAULT 0,
ID_DISPOSITIVO TEXT NOT NULL
);

CREATE TABLE PARTIDAS_INVENTARIO_MOVIL(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
GUID TEXT NOT NULL UNIQUE,
ID_INVENTARIO INTEGER NOT NULL,
ARTICULO TEXT NOT NULL,
NOMBRE TEXT NOT NULL,
LINEA TEXT NOT NULL,
CANTIDAD REAL NOT NULL DEFAULT 0,
ELIMINADO INT NOT NULL DEFAULT 0,
FOREIGN KEY (ID_INVENTARIO) REFERENCES INVENTARIO_MOVIL(ID)
);

CREATE TABLE PRODS(
ARTICULO TEXT PRIMARY KEY NOT NULL,
DESCRIP TEXT NOT NULL,
LINEA TEXT NOT NULL);

CREATE TABLE CLAVESADD(
clave TEXT PRIMARY KEY NOT NULL,
articulo TEXT NOT NULL,
cantidad INTEGER);

CREATE TABLE LINEAS(
LINEA TEXT PRIMARY KEY NOT NULL,
DESCRIP TEXT NOT NULL);
    
CREATE TABLE ALMACEN(
Almacen TEXT PRIMARY KEY  NOT NULL,
Descrip TEXT NOT NULL);
           





